### ISSUE TITLE
Automatic cleanup for dead mailslots

### ISSUE THREAD

**Issue by 0-173** [mrft/Wyphon#3]
In LocalMessageBroadcast:

When a partner sees that it can't reach one of the other partners while trying to write a message to it, it will broadcast a goodbye message in place of this dead partner and do the cleanup of the shared memory.

**Comment by mrft** [comment]
Detection only happens in 'send message to all partners', AFTER we sent all messages, because otherwise when cleaning up, we would be changing the maps, while they are being used to iterate through all partners.
