### ISSUE TITLE
wyphon website

### ISSUE THREAD

**Issue by vdmokstati** [mrft/Wyphon#8]
@mrft .. could you get in touch please.. i have good news..;)

**Comment by vdmokstati** [comment]
@meliody as well :+1:

**Comment by mrft** [comment]
What is the good news?

2013/8/20 vdmokstati notifications@github.com

**Comment by vdmokstati** [comment]
well.. since you kicked off the project i got present for you - wyphon.com
when you ready.. lets do this!! 

I really want to see this project happening... ;) <3
vdmokstati - gmail - com

**Comment by mrft** [comment]
Great.

Sorry for the late response...

Could you make it point to wyphon.wordpress.com for now?

2013/8/21 vdmokstati notifications@github.com

**Comment by vdmokstati** [comment]
could you email vdmokstati@gmail.com plz ;)

**Comment by vdmokstati** [comment]
i made a domain redirect... just as happy to host it.. and i got logo made... buzz me
